go.property("linear_velocity", 100)

function init(self)
	self.move_to_spot = nil
	self.moving = false
end

function go_to(self, dt)
	self.moving = true
	local targetPos = go.get_position(self.move_to_spot)
	go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, targetPos, go.EASING_INCUBIC, 2)
end

function on_message(self, message_id, message, sender)
	if (message_id == hash("move_to") and not self.moving) then
		self.move_to_spot = message["spot"]
		go_to(self, self.move_to_spot)
	end
end
